import type { SmartHeaderAction, SmartHeaderPreferences } from "@/lib/smartHeaderTypes";

export const DEFAULT_SMART_HEADER_PREFERENCES: SmartHeaderPreferences = {
  dismissedActionIds: [],
  enabled: true,
  hiddenCategories: [],
  preferredCategories: [],
};

export const EMPTY_SMART_HEADER_ACTION: SmartHeaderAction = {
  accentColor: "#8EA4C8",
  category: "setup",
  iconKey: "status",
  id: "empty_caught_up",
  primaryLabel: "Open Health",
  priority: 0,
  route: "/health",
  secondaryLabel: "Scan something",
  source: "placeholder",
  subtitle: "Nothing urgent right now",
  title: "You're all caught up",
  type: "open",
  visualType: "statusBadge",
};

export const PLACEHOLDER_SMART_HEADER_ACTIONS: SmartHeaderAction[] = [
  {
    accentColor: "#C96A2B",
    category: "workout",
    iconKey: "activity/dumbbell",
    id: "placeholder_workout_due",
    primaryLabel: "Start workout",
    priority: 80,
    route: "/fitness",
    secondaryLabel: "View plan",
    source: "fitness",
    subtitle: "29-day strength plan starts soon",
    title: "You're right on time",
    type: "start",
    visualType: "workoutBars",
  },
  {
    accentColor: "#6D7DF2",
    category: "mood",
    emoji: "🙂 😐 😔 😤 😴",
    iconKey: "smile",
    id: "placeholder_mood_check",
    primaryLabel: "Log mood",
    priority: 45,
    route: "/mental-health",
    secondaryLabel: "Skip",
    source: "health",
    subtitle: "Quick mood check-in",
    title: "How are you feeling?",
    type: "quickLog",
    visualType: "moodEmojiRow",
  },
  {
    accentColor: "#35A96B",
    category: "water",
    iconKey: "droplet",
    id: "placeholder_water_log",
    primaryLabel: "+250ml",
    priority: 50,
    route: "/food",
    secondaryLabel: "More",
    source: "food",
    subtitle: "Keep hydration on track",
    title: "Did you drink water?",
    type: "quickLog",
    visualType: "waterDrops",
  },
  {
    accentColor: "#35A96B",
    category: "nutrition",
    iconKey: "bowl",
    id: "placeholder_lunch_log",
    primaryLabel: "Log meal",
    priority: 55,
    route: "/food",
    secondaryLabel: "Scan food",
    source: "food",
    subtitle: "Add meal or scan food",
    title: "Lunch not logged",
    type: "quickLog",
    visualType: "mealChips",
  },
  {
    accentColor: "#56C596",
    category: "medication",
    iconKey: "pill",
    id: "placeholder_medication_due",
    primaryLabel: "Mark taken",
    priority: 95,
    privacyLevel: "private",
    route: "/medication",
    secondaryLabel: "View schedule",
    source: "medication",
    subtitle: "Next dose is ready",
    title: "Medication reminder",
    type: "reminder",
    visualType: "pillRow",
  },
  {
    accentColor: "#A78BFA",
    category: "supplements",
    iconKey: "capsule/spark",
    id: "placeholder_supplements_check",
    primaryLabel: "Mark taken",
    priority: 42,
    route: "/supplements",
    secondaryLabel: "View stack",
    source: "health",
    subtitle: "Mark today's stack",
    title: "Supplement check",
    type: "quickLog",
    visualType: "pillRow",
  },
  {
    accentColor: "#F4B18A",
    category: "baby",
    iconKey: "bottle/baby",
    id: "placeholder_baby_feed",
    primaryLabel: "Add feed",
    priority: 75,
    route: "/baby-child",
    secondaryLabel: "More logs",
    source: "babyChild",
    subtitle: "Add baby feed, diaper, or sleep",
    title: "Log feed",
    type: "quickLog",
    visibility: "babyParent",
    visualType: "babyTimeline",
  },
  {
    accentColor: "#D8B49C",
    category: "pregnancy",
    iconKey: "baby/heart",
    id: "placeholder_pregnancy_check",
    primaryLabel: "Check in",
    priority: 70,
    route: "/pregnancy",
    secondaryLabel: "Setup",
    source: "pregnancy",
    subtitle: "Add symptoms or appointment",
    title: "Week check-in",
    type: "quickLog",
    visibility: "pregnancy",
    visualType: "pregnancyMilestones",
  },
  {
    accentColor: "#C2185B",
    category: "cycle",
    iconKey: "calendar-heart",
    id: "placeholder_cycle_check",
    primaryLabel: "Log symptom",
    priority: 60,
    privacyLevel: "private",
    route: "/cycle",
    secondaryLabel: "View cycle",
    source: "cycle",
    subtitle: "Log symptoms privately",
    title: "Cycle check-in",
    type: "quickLog",
    visibility: "female",
    visualType: "cycleCalendarDots",
  },
  {
    accentColor: "#E5C94C",
    category: "family",
    iconKey: "users",
    id: "placeholder_family_updates",
    primaryLabel: "View updates",
    priority: 58,
    route: "/family-circle",
    secondaryLabel: "Mark checked",
    source: "family",
    subtitle: "2 shared updates today",
    title: "Family updates",
    type: "review",
    visibility: "family",
    visualType: "familyBubbles",
  },
  {
    accentColor: "#60A5FA",
    category: "scan",
    iconKey: "scan-frame",
    id: "placeholder_quick_scan",
    primaryLabel: "Open camera",
    priority: 25,
    route: "/scan",
    secondaryLabel: "History",
    source: "scan",
    subtitle: "Food, medication, or document",
    title: "Quick scan",
    type: "scan",
    visualType: "scanFrame",
  },
  {
    accentColor: "#8EA4C8",
    category: "records",
    iconKey: "folder-heart",
    id: "placeholder_records_add",
    primaryLabel: "Add record",
    priority: 30,
    route: "/records",
    secondaryLabel: "View records",
    source: "health",
    subtitle: "Keep documents ready",
    title: "Add health record",
    type: "open",
    visualType: "recordsBadge",
  },
  {
    accentColor: "#64748B",
    category: "sleep",
    iconKey: "moon",
    id: "placeholder_sleep_check",
    primaryLabel: "Log sleep",
    priority: 40,
    route: "/health",
    secondaryLabel: "Later",
    source: "health",
    subtitle: "Log last night's sleep",
    title: "Sleep check-in",
    type: "quickLog",
    visualType: "sleepBars",
  },
  {
    accentColor: "#EF4444",
    category: "vitals",
    iconKey: "heart-pulse",
    id: "placeholder_vitals_check",
    primaryLabel: "Add reading",
    priority: 35,
    route: "/health",
    secondaryLabel: "View health",
    source: "health",
    subtitle: "Add your latest reading",
    title: "Vitals check",
    type: "quickLog",
    visualType: "pulseLine",
  },
];
