export type HealthTileVisualType =
  | "icon_svg"
  | "mini_line"
  | "mini_bar"
  | "emoji_status"
  | "timeline"
  | "log_stack"
  | "checklist"
  | "calendar_dot"
  | "status_badge"
  | "avatar_stack"
  | "setup_card"
  | "none";

export type HealthRealmCategory = "realm" | "tracker" | "setup" | "record" | "family";
export type HealthRealmVisibility = "all" | "female" | "male" | "child" | "pregnancy" | "family";

export type HealthRealmConfig = {
  id: string;
  label: string;
  shortLabel?: string;
  category: HealthRealmCategory;
  route: string;
  icon: string;
  emoji?: string;
  accentColor: string;
  lightTileBackground?: string;
  darkTileBackground?: string;
  visualType: HealthTileVisualType;
  placeholderPrimary: string;
  placeholderSecondary: string;
  placeholderContext?: string;
  description: string;
  placeholderActions: string[];
  setupRequired?: boolean;
  enabledByDefault?: boolean;
  visibility?: HealthRealmVisibility;
};

export const DEFAULT_HEALTH_TILE_IDS = ["nutrition_overview", "medication", "fitness", "family"] as const;

export const HEALTH_REALM_REGISTRY = [
  {
    id: "nutrition_overview",
    label: "Nutrition",
    shortLabel: "Food plan",
    category: "realm",
    route: "/food",
    icon: "utensils",
    emoji: "\u{1F957}",
    accentColor: "#35A96B",
    lightTileBackground: "#CDEFD9",
    darkTileBackground: "#284539",
    visualType: "mini_bar",
    placeholderPrimary: "34% logged",
    placeholderSecondary: "Meals, water, protein",
    placeholderContext: "Daily nutrition",
    description: "Track meals, hydration, protein, and food goals in one place.",
    placeholderActions: ["Log meal", "Add water", "Set nutrition goal"],
    enabledByDefault: true,
    visibility: "all",
  },
  {
    id: "water_tracking",
    label: "Water",
    shortLabel: "Hydration",
    category: "tracker",
    route: "/food/water",
    icon: "droplet",
    emoji: "\u{1F4A7}",
    accentColor: "#35A96B",
    visualType: "log_stack",
    placeholderPrimary: "5/8 cups",
    placeholderSecondary: "Daily hydration",
    description: "Track daily hydration, cup goals, and reminders.",
    placeholderActions: ["Add water log", "Set daily target", "Reminder settings"],
    visibility: "all",
  },
  {
    id: "meal_logging",
    label: "Meals",
    shortLabel: "Meal log",
    category: "tracker",
    route: "/food/meals",
    icon: "bowl",
    emoji: "\u{1F37D}\uFE0F",
    accentColor: "#35A96B",
    visualType: "checklist",
    placeholderPrimary: "2/3 meals",
    placeholderSecondary: "Lunch not logged",
    description: "Log breakfast, lunch, dinner, and meal notes.",
    placeholderActions: ["Log breakfast", "Log lunch", "Review today"],
    visibility: "all",
  },
  {
    id: "protein_goal",
    label: "Protein",
    shortLabel: "Protein",
    category: "tracker",
    route: "/food/goals/protein",
    icon: "egg",
    emoji: "\u{1F95A}",
    accentColor: "#219653",
    visualType: "mini_bar",
    placeholderPrimary: "70g / 120g",
    placeholderSecondary: "Protein target",
    description: "Track protein intake against your daily target.",
    placeholderActions: ["Add protein", "Set target", "Review meals"],
    visibility: "all",
  },
  {
    id: "medication",
    label: "Medication",
    shortLabel: "Antibiotic course",
    category: "tracker",
    route: "/medication",
    icon: "pill",
    emoji: "\u{1F48A}",
    accentColor: "#56C596",
    lightTileBackground: "#C9F4D2",
    darkTileBackground: "#294C40",
    visualType: "checklist",
    placeholderPrimary: "3/4 done",
    placeholderSecondary: "Next dose 19:00",
    placeholderContext: "Today",
    description: "Track medication schedules, doses, and reminders.",
    placeholderActions: ["Log dose", "Add medication", "Reminder settings"],
    visibility: "all",
  },
  {
    id: "supplements",
    label: "Supplements",
    shortLabel: "Supplement plan",
    category: "tracker",
    route: "/supplements",
    icon: "capsule",
    emoji: "\u2728",
    accentColor: "#A78BFA",
    lightTileBackground: "#E3D8FF",
    darkTileBackground: "#443A61",
    visualType: "log_stack",
    placeholderPrimary: "5/7 days",
    placeholderSecondary: "Weekly consistency",
    description: "Track supplement routines and weekly consistency.",
    placeholderActions: ["Log supplement", "Add supplement", "Review week"],
    visibility: "all",
  },
  {
    id: "refill_reminders",
    label: "Refills",
    shortLabel: "Refills",
    category: "tracker",
    route: "/medication/refills",
    icon: "bell",
    emoji: "\u{1F514}",
    accentColor: "#56C596",
    visualType: "status_badge",
    placeholderPrimary: "1 refill",
    placeholderSecondary: "Due this week",
    description: "Track medication refills and pharmacy reminders.",
    placeholderActions: ["Add refill", "Set reminder", "View pharmacy"],
    visibility: "all",
  },
  {
    id: "fitness",
    label: "Fitness",
    shortLabel: "29-day plan",
    category: "realm",
    route: "/fitness",
    icon: "activity",
    emoji: "\u{1F525}",
    accentColor: "#C96A2B",
    lightTileBackground: "#F7D9C2",
    darkTileBackground: "#4A342A",
    visualType: "mini_line",
    placeholderPrimary: "55%",
    placeholderSecondary: "Weekly goal",
    placeholderContext: "Sunday start",
    description: "Track workouts, activity, body metrics, and weekly goals.",
    placeholderActions: ["Start workout", "View plan", "Set weekly goal"],
    enabledByDefault: true,
    visibility: "all",
  },
  {
    id: "steps",
    label: "Steps",
    shortLabel: "Steps",
    category: "tracker",
    route: "/fitness/steps",
    icon: "footprints",
    emoji: "\u{1F45F}",
    accentColor: "#C96A2B",
    visualType: "mini_line",
    placeholderPrimary: "7,200",
    placeholderSecondary: "10k daily target",
    description: "Track steps, daily movement, and walking streaks.",
    placeholderActions: ["Sync steps", "Set daily target", "View trend"],
    visibility: "all",
  },
  {
    id: "workout_plan",
    label: "Workout",
    shortLabel: "Workout",
    category: "tracker",
    route: "/fitness/plans",
    icon: "dumbbell",
    emoji: "\u{1F3CB}\uFE0F",
    accentColor: "#C96A2B",
    visualType: "checklist",
    placeholderPrimary: "Leg day",
    placeholderSecondary: "Planned today",
    description: "Plan workouts and track completed sessions.",
    placeholderActions: ["Start workout", "Edit plan", "View history"],
    visibility: "all",
  },
  {
    id: "weight_tracking",
    label: "Weight",
    shortLabel: "Weight",
    category: "tracker",
    route: "/health/weight",
    icon: "scale",
    emoji: "\u2696\uFE0F",
    accentColor: "#8EA4C8",
    visualType: "mini_line",
    placeholderPrimary: "72.4 kg",
    placeholderSecondary: "Weekly trend",
    description: "Track weight and body trend changes over time.",
    placeholderActions: ["Add weight", "View chart", "Set target"],
    visibility: "all",
  },
  {
    id: "health_overview",
    label: "Health",
    shortLabel: "Overview",
    category: "realm",
    route: "/health",
    icon: "heart-pulse",
    emoji: "\u2764\uFE0F",
    accentColor: "#101828",
    lightTileBackground: "#F8FAFC",
    darkTileBackground: "#3F3F46",
    visualType: "status_badge",
    placeholderPrimary: "2 alerts",
    placeholderSecondary: "Needs attention",
    description: "Review health alerts, trackers, and setup prompts.",
    placeholderActions: ["Review alerts", "Edit board", "Privacy settings"],
    visibility: "all",
  },
  {
    id: "vitals",
    label: "Vitals",
    shortLabel: "Vitals",
    category: "record",
    route: "/health/vitals",
    icon: "heart-pulse",
    emoji: "\u{1FAC0}",
    accentColor: "#EF4444",
    visualType: "mini_line",
    placeholderPrimary: "78 bpm",
    placeholderSecondary: "Last checked today",
    description: "Track key vitals such as heart rate and blood pressure.",
    placeholderActions: ["Add reading", "View trend", "Set alert"],
    visibility: "all",
  },
  {
    id: "sleep",
    label: "Sleep",
    shortLabel: "Sleep",
    category: "tracker",
    route: "/health/sleep",
    icon: "moon",
    emoji: "\u{1F319}",
    accentColor: "#64748B",
    visualType: "timeline",
    placeholderPrimary: "6h 45m",
    placeholderSecondary: "Last night",
    description: "Track sleep duration, rhythm, and bedtime routines.",
    placeholderActions: ["Log sleep", "Set bedtime", "View rhythm"],
    visibility: "all",
  },
  {
    id: "mental_health",
    label: "Mood",
    shortLabel: "Check-in",
    category: "tracker",
    route: "/health/mood",
    icon: "smile",
    emoji: "\u{1F642}",
    accentColor: "#F59E0B",
    visualType: "emoji_status",
    placeholderPrimary: "Calm",
    placeholderSecondary: "Logged today",
    description: "Track mood check-ins, notes, and emotional trends.",
    placeholderActions: ["Log mood", "Add note", "View trend"],
    visibility: "all",
  },
  {
    id: "cycle",
    label: "Cycle",
    shortLabel: "Cycle tracking",
    category: "tracker",
    route: "/cycle",
    icon: "calendar-heart",
    emoji: "\u{1F338}",
    accentColor: "#C2185B",
    lightTileBackground: "#F4C8DA",
    darkTileBackground: "#4D2637",
    visualType: "calendar_dot",
    placeholderPrimary: "Day 18",
    placeholderSecondary: "Fertile window",
    description: "Track period dates, symptoms, predictions, and privacy.",
    placeholderActions: ["Log period", "Add symptoms", "Privacy settings"],
    visibility: "female",
  },
  {
    id: "period_tracking",
    label: "Period",
    shortLabel: "Period",
    category: "tracker",
    route: "/cycle/period",
    icon: "droplet-calendar",
    emoji: "\u{1FA78}",
    accentColor: "#C2185B",
    visualType: "calendar_dot",
    placeholderPrimary: "4 days left",
    placeholderSecondary: "Predicted start",
    description: "Track period predictions and recent cycle history.",
    placeholderActions: ["Log period", "Add symptoms", "Privacy settings"],
    visibility: "female",
  },
  {
    id: "contraception",
    label: "Contraception",
    shortLabel: "Contraception",
    category: "tracker",
    route: "/cycle/contraception",
    icon: "shield-clock",
    emoji: "\u{1F6E1}\uFE0F",
    accentColor: "#C2185B",
    visualType: "timeline",
    placeholderPrimary: "Active",
    placeholderSecondary: "Reminder tomorrow",
    description: "Track contraception status and reminders.",
    placeholderActions: ["Log reminder", "Edit schedule", "Privacy settings"],
    visibility: "female",
  },
  {
    id: "pregnancy",
    label: "Pregnancy",
    shortLabel: "Pregnancy plan",
    category: "realm",
    route: "/pregnancy",
    icon: "baby-heart",
    emoji: "\u{1F930}",
    accentColor: "#D8B49C",
    lightTileBackground: "#F1DED2",
    darkTileBackground: "#504138",
    visualType: "timeline",
    placeholderPrimary: "Week 22",
    placeholderSecondary: "Next checkup",
    description: "Track pregnancy milestones, checkups, and weekly tasks.",
    placeholderActions: ["View week", "Add appointment", "Checklist"],
    visibility: "pregnancy",
  },
  {
    id: "pregnancy_setup",
    label: "Pregnancy Setup",
    shortLabel: "Setup",
    category: "setup",
    route: "/pregnancy/setup",
    icon: "clipboard-plus",
    emoji: "\u{1F4CB}",
    accentColor: "#D8B49C",
    visualType: "setup_card",
    placeholderPrimary: "Setup needed",
    placeholderSecondary: "Add due date",
    description: "Add due date, appointment reminders, and weekly milestones.",
    placeholderActions: ["Add due date", "Add first appointment", "Choose pregnancy reminders"],
    setupRequired: true,
    visibility: "pregnancy",
  },
  {
    id: "pregnancy_checklist",
    label: "Pregnancy Tasks",
    shortLabel: "Tasks",
    category: "tracker",
    route: "/pregnancy/checklist",
    icon: "list-check",
    emoji: "\u2705",
    accentColor: "#D8B49C",
    visualType: "checklist",
    placeholderPrimary: "6/10 done",
    placeholderSecondary: "This week",
    description: "Track pregnancy tasks and weekly preparation.",
    placeholderActions: ["Add task", "Mark complete", "View week"],
    visibility: "pregnancy",
  },
  {
    id: "baby_care",
    label: "Baby Care",
    shortLabel: "Baby care",
    category: "tracker",
    route: "/baby-child",
    icon: "baby",
    emoji: "\u{1F476}",
    accentColor: "#F4B18A",
    lightTileBackground: "#F8DDCC",
    darkTileBackground: "#514036",
    visualType: "log_stack",
    placeholderPrimary: "2 logs",
    placeholderSecondary: "Feeding due soon",
    description: "Track baby care logs, feeding, growth, and reminders.",
    placeholderActions: ["Add care log", "Add feeding", "View schedule"],
    visibility: "child",
  },
  {
    id: "feeding",
    label: "Feeding",
    shortLabel: "Feeding",
    category: "tracker",
    route: "/baby-child/feeding",
    icon: "bottle",
    emoji: "\u{1F37C}",
    accentColor: "#F4B18A",
    visualType: "timeline",
    placeholderPrimary: "5 feeds",
    placeholderSecondary: "Last feed 14:20",
    description: "Track feeding sessions, amounts, and timing.",
    placeholderActions: ["Add feeding", "Set reminder", "View today"],
    visibility: "child",
  },
  {
    id: "vaccines",
    label: "Vaccines",
    shortLabel: "Vaccines",
    category: "tracker",
    route: "/baby-child/vaccines",
    icon: "syringe",
    emoji: "\u{1F489}",
    accentColor: "#F4B18A",
    visualType: "status_badge",
    placeholderPrimary: "1 due",
    placeholderSecondary: "Upcoming vaccine",
    description: "Track vaccine schedules and upcoming appointments.",
    placeholderActions: ["Add vaccine", "Add appointment", "View schedule"],
    visibility: "child",
  },
  {
    id: "growth",
    label: "Growth",
    shortLabel: "Growth",
    category: "tracker",
    route: "/baby-child/growth",
    icon: "ruler",
    emoji: "\u{1F4CF}",
    accentColor: "#F4B18A",
    visualType: "mini_line",
    placeholderPrimary: "4.27 kg",
    placeholderSecondary: "Last update",
    description: "Track growth, weight, length, and changes over time.",
    placeholderActions: ["Add measurement", "View chart", "Set reminder"],
    visibility: "child",
  },
  {
    id: "family",
    label: "Family",
    shortLabel: "Family updates",
    category: "family",
    route: "/circle",
    icon: "users",
    emoji: "\u{1F46A}",
    accentColor: "#E5C94C",
    lightTileBackground: "#F5EDB8",
    darkTileBackground: "#514B2F",
    visualType: "avatar_stack",
    placeholderPrimary: "5 updates",
    placeholderSecondary: "2 shared today",
    description: "See family health updates and shared care activity.",
    placeholderActions: ["Open circle", "Invite member", "Review updates"],
    enabledByDefault: true,
    visibility: "family",
  },
  {
    id: "records",
    label: "Records",
    shortLabel: "Records",
    category: "record",
    route: "/records",
    icon: "folder-heart",
    emoji: "\u{1F4C1}",
    accentColor: "#8EA4C8",
    lightTileBackground: "#D8E2F1",
    darkTileBackground: "#354152",
    visualType: "status_badge",
    placeholderPrimary: "3 files",
    placeholderSecondary: "Last updated today",
    description: "Store and review important health records.",
    placeholderActions: ["Add file", "Scan document", "View records"],
    visibility: "all",
  },
  {
    id: "scans",
    label: "AI Scan",
    shortLabel: "AI scan",
    category: "record",
    route: "/scan",
    icon: "scan-line",
    emoji: "\u{1F4F7}",
    accentColor: "#60A5FA",
    visualType: "icon_svg",
    placeholderPrimary: "Ready",
    placeholderSecondary: "Scan food or medication",
    description: "Scan food, medication, or documents for quick capture.",
    placeholderActions: ["Start scan", "Scan food", "Scan medication"],
    visibility: "all",
  },
  {
    id: "medical_aid",
    label: "Medical Aid",
    shortLabel: "Medical aid",
    category: "setup",
    route: "/health/medical-aid",
    icon: "badge-plus",
    emoji: "\u{1FAAA}",
    accentColor: "#8EA4C8",
    visualType: "setup_card",
    placeholderPrimary: "Connect later",
    placeholderSecondary: "Placeholder setup",
    description: "Connect medical aid details and pharmacy coverage later.",
    placeholderActions: ["Add provider", "Add member number", "Search pharmacy coverage"],
    setupRequired: true,
    visibility: "all",
  },
] as const satisfies readonly HealthRealmConfig[];

export type HealthRealmConfigId = (typeof HEALTH_REALM_REGISTRY)[number]["id"];

export const HEALTH_REALM_CONFIG_BY_ID: Record<string, HealthRealmConfig> = Object.fromEntries(
  HEALTH_REALM_REGISTRY.map((config) => [config.id, config])
);

export const HEALTH_REALM_CONFIG_BY_ROUTE: Record<string, HealthRealmConfig> = Object.fromEntries(
  HEALTH_REALM_REGISTRY.map((config) => [config.route, config])
);

export function getHealthRealmConfig(id: string): HealthRealmConfig {
  return HEALTH_REALM_CONFIG_BY_ID[id] ?? HEALTH_REALM_CONFIG_BY_ID.nutrition_overview;
}

export function getHealthRealmConfigByRoute(route: string): HealthRealmConfig | undefined {
  return HEALTH_REALM_CONFIG_BY_ROUTE[route];
}
