apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.workoutactivity'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()

android {
  namespace "expo.modules.workoutactivity"

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 23)
    compileSdkVersion safeExtGet("compileSdkVersion", 36)
    targetSdkVersion safeExtGet("targetSdkVersion", 36)
  }
}

dependencies {
  implementation "androidx.core:core-ktx:1.13.1"
}

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
